packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@brillout/release-me': ^0.4.1
  '@hattip/router': ^0.0.48
  '@swc/core': ^1.7.26
  '@types/express': ^4.17.21
  '@types/node': ^20.16.5
  express: ^4.21.0
  fastify: ^4.28.1
  h3: ^1.12.0
  hono: ^4.6.1
  rimraf: ^6.0.1
  tsup: ^8.2.4
  tsx: ^4.19.1
  typescript: ^5.6.2
  vite: ^5.4.5
  vitest: ^2.1.1
  wrangler: ^3.78.2
