packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20250109.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.10.7
  '@types/express': ^4.17.21
  '@types/node': ^20.17.12
  '@webroute/route': ^0.8.0
  elysia: ^1.2.10
  express: ^4.21.2
  fastify: ^5.2.1
  h3: ^1.13.1
  hono: ^4.6.16
  rimraf: ^6.0.1
  tsup: ^8.3.5
  tsx: ^4.19.2
  typescript: ^5.7.3
  vite: ^6.0.7
  vitest: ^2.1.8
  wrangler: ^3.101.0
