packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20250214.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.10.18
  '@types/express': ^4.17.21
  '@types/node': ^20.17.19
  '@webroute/route': ^0.8.0
  elysia: ^1.2.21
  express: ^4.21.2
  fastify: ^5.2.1
  h3: ^1.15.1
  hono: ^4.7.2
  rimraf: ^6.0.1
  tsup: ^8.3.6
  tsx: ^4.19.3
  typescript: ^5.7.3
  vite: ^6.1.1
  vitest: ^3.0.6
  wrangler: ^3.109.3
