packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.9.3
  '@types/express': ^4.17.21
  '@types/node': ^20.17.9
  elysia: ^1.1.25
  express: ^4.21.1
  fastify: ^5.1.0
  h3: ^1.13.0
  hono: ^4.6.12
  rimraf: ^6.0.1
  tsup: ^8.3.5
  tsx: ^4.19.2
  typescript: ^5.7.2
  vite: ^6.0.2
  vitest: ^2.1.7
  wrangler: ^3.91.0
