packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20250124.3
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.10.9
  '@types/express': ^4.17.21
  '@types/node': ^20.17.16
  '@webroute/route': ^0.8.0
  elysia: ^1.2.10
  express: ^4.21.2
  fastify: ^5.2.1
  h3: ^1.14.0
  hono: ^4.6.19
  rimraf: ^6.0.1
  tsup: ^8.3.6
  tsx: ^4.19.2
  typescript: ^5.7.3
  vite: ^6.0.11
  vitest: ^3.0.4
  wrangler: ^3.105.1
