packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20250327.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.11.13
  '@types/express': ^4.17.21
  '@types/node': ^20.17.19
  '@webroute/route': ^0.8.0
  elysia: ^1.2.25
  express: ^4.21.2
  fastify: ^5.2.2
  h3: ^1.15.1
  hono: ^4.7.5
  rimraf: ^6.0.1
  tsup: ^8.4.0
  tsx: ^4.19.3
  typescript: ^5.8.2
  vite: ^6.2.2
  vitest: ^3.0.9
  wrangler: ^4.6.0
