packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.8.0
  '@types/express': ^4.17.21
  '@types/node': ^20.17.6
  elysia: ^1.1.24
  express: ^4.21.1
  fastify: ^5.1.0
  h3: ^1.13.0
  hono: ^4.6.9
  rimraf: ^6.0.1
  tsup: ^8.3.5
  tsx: ^4.19.2
  typescript: ^5.6.3
  vite: ^5.4.10
  vitest: ^2.1.4
  wrangler: ^3.84.1
