packages:
  - "packages/*"
  - "examples/*"
  - "tests-examples/*"
  - "docs"

catalog:
  "@hattip/router": "^0.0.48"
  "@types/express": "^4.17.21"
  "express": "^4.19.2"
  "fastify": "^4.28.1"
  "h3": "^1.12.0"
  "hono": "^4.5.11"
  "@types/node": "^20.16.5"
  "@brillout/release-me": "^0.4.1"
