packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@brillout/release-me': ^0.4.2
  '@hattip/router': ^0.0.48
  '@swc/core': ^1.7.28
  '@types/express': ^4.17.21
  '@types/node': ^20.16.10
  express: ^4.21.0
  fastify: ^5.0.0
  h3: ^1.13.0
  hono: ^4.6.3
  rimraf: ^6.0.1
  tsup: ^8.3.0
  tsx: ^4.19.1
  typescript: ^5.6.2
  vite: ^5.4.8
  vitest: ^2.1.2
  wrangler: ^3.80.0
