name: CI tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref || github.run_id }}"
  cancel-in-progress: true

defaults:
  run:
    working-directory: .

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [20]
        include:
          - os: ubuntu-latest
            node_version: 18
          - os: ubuntu-latest
            node_version: 22
      fail-fast: false
    name: "CI tests on node-${{ matrix.node_version }}, ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set Node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          check-latest: true
          cache: "pnpm"

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - name: Install
        run: pnpm install

      - run: pnpm playwright install chromium

      - name: Build
        run: pnpm run build

      - name: Run lint
        if: ${{ matrix.os != 'windows-latest' }}
        run: pnpm run lint

      - name: Run typecheck
        if: ${{ matrix.os != 'windows-latest' }}
        run: pnpm run test:typecheck

      - name: Run tests
        if: ${{ matrix.os != 'windows-latest' }}
        run: pnpm run test
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  release-please-beta:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-beta-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.head_ref || github.ref_name }}
