name: Publish Any Commit
on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'pkg-pr-new')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: pnpx pkg-pr-new publish './packages/*'
