on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-beta-merge

jobs:
  release-please-beta-merge:
    if: contains(github.event.pull_request.labels.*.name, 'beta')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-beta-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.head_ref || github.ref_name }}
          skip-github-pull-request: true

      - uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.releases_created }}

      - name: Setup Node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - run: pnpm run build
        if: ${{ steps.release.outputs.releases_created }}

      - run: pnpm publish --tag beta --access public --no-git-checks -r
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
